apps/accounts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from apps.accounts import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", login_required(views.CustomLogoutView.as_view()), name="logout"),
    path("change_password/",
         login_required(views.CustomPasswordChangeView.as_view()),
         name="change-password"),
]

apps/core/urls.py
from django.urls import path

from apps.core import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

# Admin customization
admin.site.site_header = settings.WEBSITE_NAME
admin.site.site_title = f"{settings.WEBSITE_NAME} Administration"
admin.site.index_title = f"{settings.WEBSITE_NAME} - Admin"

# URL Patterns for installed apps
urlpatterns = [
    path("", include("apps.core.urls")),
    path('accounts/', include("apps.accounts.urls")),
    path('admin/', admin.site.urls),
]

# If DEBUG is true, load Dev Apps URLs
if settings.DEBUG:
    urlpatterns.extend([
        path("__reload__/", include("django_browser_reload.urls")),
    ])

apps/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from simple_history.models import HistoricalRecords


class CustomUserManager(BaseUserManager):
    """ Custom User Manager for CustomUser Model. """

    def create_user(self, email, password=None, **extra_fields):
        """ Method to create a Base CustomUser """

        if not email:
            raise ValueError("The Email field must be set")

        # Normalize the email address (convert to lowercase) and create a user instance.
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)  # Set the user's password securely.
        user.save()  # Save the user to the database.
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """ Method to create a superuser with staff and superuser privileges. """

        # Set default values for is_staff and is_superuser if not provided.
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        # Ensure that is_staff and is_superuser are True for a superuser.
        if (extra_fields.get("is_staff") is not True
                or extra_fields.get("is_superuser") is not True):
            raise ValueError("Superuser must have is_staff=True and is_superuser=True.")

        # Call the create_user method to create the superuser.
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    """ A Custom user model that extends AbstractUser. """

    # Replace the username field with an email field that must be unique.
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255)

    # Remove the username, first_name and last_name field as it's not needed.
    first_name = None
    last_name = None
    username = None

    # Add historical records tracking to the model.
    history = HistoricalRecords()

    objects = CustomUserManager()  # Use the custom user manager for user creation.

    # Set the email field as the username field for authentication.
    USERNAME_FIELD = "email"

    # No additional required fields for user creation.
    REQUIRED_FIELDS = []

    # Define a human-readable string representation of the user (email).
    def __str__(self):
        return self.email

    # Overwrite get_full_name method
    def get_full_name(self):
        return self.name

    # Overwrite get_short_name method
    def get_short_name(self):
        return self.name.split(" ")[0]

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

apps/accounts/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm


class LoginForm(AuthenticationForm):
    """ Custom login form that extends the AuthenticationForm. """

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        # FormHelper instance for better form rendering control.
        self.helper = FormHelper()

        # layout for the form using Crispy Forms Layout.
        self.helper.layout = Layout(
            'username',
            'password',
            Submit('submit', 'Login', css_class="btn")
        )


class CustomPasswordChangeForm(PasswordChangeForm):
    """ Custom Password Change Form that extends PassWordChangeForm """

    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)

        # FormHelper instance for better form rendering control.
        self.helper = FormHelper()

        # layout for the form using Crispy Forms Layout.
        self.helper.layout = Layout(
            'old_password',
            'new_password1',
            'new_password2',
            Submit('submit', 'Change Password', css_class="btn")
        )

apps/accounts/views.py
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.contrib import messages
from apps.accounts.forms import CustomPasswordChangeForm, LoginForm


class CustomLogoutView(LogoutView):
    """ Custom logout view """
    next_page = settings.LOGOUT_REDIRECT_URL


@method_decorator(never_cache, name="dispatch")
class CustomLoginView(LoginView):
    """ Custom login View """
    template_name = 'accounts/login.html'
    form_class = LoginForm

    def form_valid(self, form):
        user = form.get_user()
        messages.success(self.request, f'Logged in as {user.email}')
        return super().form_valid(form)


class CustomPasswordChangeView(PasswordChangeView):
    """ Custom Password Change View """
    form_class = CustomPasswordChangeForm
    template_name = 'accounts/change_password.html'  # Replace with your template name
    success_url = reverse_lazy("core:index")

apps/core/views.py
from django.shortcuts import render


def index(request):
    """ Dashboard View """
    return render(request, template_name="core/index.html")

templates/accounts/change_password.html
{% extends 'base.html' %}

{% load tailwind_filters %}
{% load crispy_forms_tags %}

{% block title %} - Change Password {% endblock %}


{% block main %}
    <div class="flex items-center justify-center">
        <div class="bg-white drop-shadow rounded w-10/12 md:w-96 p-6">
            <div class="text-2xl">Change Password</div>
            <hr class="mt-2 mb-4">
            {% crispy form %}
        </div>

    </div>

{% endblock %}

templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {# Load template tags #}
    {% load static %}
    {% load tailwind_filters %}
    {% load crispy_forms_tags %}

    {# Meta tags #}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {# Load static files #}
    <link rel="stylesheet" href="{% static 'css/tailwind.css' %}">

    {# Icons and Title #}
    <link rel="icon" href="{% static 'images/logo.png' %}">
    <title>Login - {{ WEBSITE_NAME }}</title>
</head>
<body class="bg-gray-100 max-w-screen h-screen w-screen flex justify-center">
<div class="mt-32">
    {% if request.user.is_authenticated %}
        <div class="bg-red-200 text-red-800 px-6 py-2 border text-red-700 drop-shadow">
            <strong>Oops!</strong> Looks like you are already logged in. Click <a href="{% url 'core:index' %}"
                                                                                  class="underline"><strong>here</strong></a>
            to go back.
        </div>
    {% else %}
        <div class="bg-white p-6 drop-shadow w-11/12 sm:w-96">
            <div class="text-2xl font-semibold text-gray-600">Login</div>
            <hr class="mt-2 mb-4">
            {% crispy form %}
        </div>
    {% endif %}
</div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {# Load template tags #}
    {% load static %}
    {% load message_themes %}

    {# Meta tags #}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {# Title and Icon #}
    <title>{{ WEBSITE_NAME }}{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'images/logo.png' %}">

    {# Static Files #}
    <link rel="stylesheet" href="{% static 'css/tailwind.css' %}">
    <script src="{% static 'js/alpine__3_13_0.min.js' %}" defer></script>
    <script src="{% static 'js/htmx__1_9_5.min.js' %}"></script>
    {# Extra static block #}
    {% block extra_static %}{% endblock %}
</head>


<body class=" text-gray-700 max-w-screen bg-gray-100" x-data="{sidebarOpen: false}" @keydown.esc="sidebarOpen=false">

{# Sidebar #}
{% include "shared/sidebar.html" %}

{# Navbar #}
{% include 'shared/navbar.html' %}

{# Spacer to provide for fixed navbar #}
<div class="h-20 w-screen"></div>

{# Display messages #}
<div class="px-5">
    {% for message in messages %}
        <div class="{% message_theme message.tags %} alert flex items-center" x-data="{show:true}" x-show="show">
            <div class="grow">{{ message }}</div>
            <button class="text-indigo-700" @click="show=false">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24">
                    <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
                    <path d="M0 0h24v24H0z" fill="none"/>
                </svg>
            </button>
        </div>
    {% endfor %}
</div>

<main class="px-5">

    {# Breadcrumb #}
    {% include 'shared/breadcrumbs.html' %}

    {# Main Block #}
    <div class="mt-5">
        {% block main %}{% endblock %}
    </div>
</main>
</body>
</html>

templates/core/index.html
{% extends 'base.html' %}

{% block main %}
    <div class="bg-white p-4 drop-shadow rounded">
        Logged in as: <strong>{{ request.user.email }}</strong>
        <div class="text-xs mt-2 text-gray-500">
            <table class="text-xs mt-1 mb-2">
                <tr>
                    <td><strong>Date Joined</strong></td>
                    <td>:</td>
                    <td>{{ request.user.date_joined }}</td>
                </tr>
                <tr>
                    <td><strong>Last Login</strong></td>
                    <td>:</td>
                    <td>{{ request.user.last_login }}</td>
                </tr>
                <tr>
                    <td><strong>Is Staff</strong></td>
                    <td>:</td>
                    <td>{{ request.user.is_staff }}</td>
                </tr>
                <tr>
                    <td><strong>Is Superuser</strong></td>
                    <td>:</td>
                    <td>{{ request.user.is_superuser }}</td>
                </tr>
            </table>
            <div>
                You are seeing this because the current template is extending base.html without overwriting the main
                block.
            </div>
            <div>
                To stop seeing this, add your own main block in the template.
            </div>
        </div>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 my-8">
        {% for _ in "x"|rjust:50 %}
            <div class="bg-white p-10 p-6 rounded drop-shadow">
                <div class="text-xl font-medium">This is Card {{ forloop.counter }}</div>
                <hr class="mt-1 mb-2 border-gray-300">
                <div class="text-xs text-gray-500">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A culpa deserunt itaque laudantium officia
                    officiis quos temporibus, totam ut vel! At dicta eveniet iure, minus natus quod suscipit temporibus
                    voluptatem.
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/others/tailwind/display_form.html
{% if form.form_html %}
    {% if include_media %}{{ form.media }}{% endif %}
    {% if form_show_errors %}
        {% include "tailwind/errors.html" %}
    {% endif %}
    {{ form.form_html }}
{% else %}
    {% include "tailwind/uni_form.html" %}
{% endif %}

templates/others/tailwind/errors.html
{% if form.non_field_errors %}
  <div class="alert mb-4">
    {% if form_error_title %}
      <div class="bg-red-500 text-white font-bold rounded-t px-4 py-2">
        {{ form_error_title }}
      </div>
    {% endif %}
    <div class="border border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
      <ul>
        {{ form.non_field_errors|unordered_list }}
      </ul>
    </div>
  </div>
{% endif %}

templates/others/tailwind/errors_formset.html
{% if formset.non_form_errors %}
    <div class="alert mb-4">
        {% if formset_error_title %}
            <div class="bg-red-500 text-white font-bold rounded-t px-4 py-2">
                {{ formset_error_title }}
            </div>
        {% endif %}
        <div class="border border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
            <ul>
                {{ formset.non_form_errors|unordered_list }}
            </ul>
        </div>
    </div>
{% endif %}

templates/others/tailwind/field.html
{% load tailwind_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {# Opening Div and Label first #}

    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" class="{% if wrapper_class %}{{ wrapper_class }} {% endif %}{% if field_class %}{{ field_class }}{% else %}mb-3{% endif %}">
    {% if field.label and form_show_labels %}
        <label for="{{ field.id_for_label }}" class="{% if label_class %}{{ label_class }}{% else %}block text-gray-700 text-sm font-bold mb-2{% endif %}">
            {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
        </label>
    {% endif %}

    {# if field has a special template then use this #}
    {% if field|is_select %}
        <div class="{% if field_class %}{{ field_class }}{% else %}mb-3{% endif %}"{% if flat_attrs %} {{ flat_attrs|safe }}{% endif %}>

        {% include 'tailwind/layout/select.html' %}
    {% elif field|is_radioselect %}
        <div class="{% if field_class %}{{ field_class }}{% else %}mb-3{% endif %}"{% if flat_attrs %} {{ flat_attrs|safe }}{% endif %}>

        {% include 'tailwind/layout/radioselect.html' %}
    {% elif field|is_checkboxselectmultiple %}

        <div class="{% if field_class %}{{ field_class }}{% else %}mb-3{% endif %}"{% if flat_attrs %} {{ flat_attrs|safe }}{% endif %}>
        {% include 'tailwind/layout/checkboxselectmultiple.html' %}
    {% else %}

        {# otherwise use django rendering with additional classes added #}
        {% tailwind_field field %}
    {% endif %}

    {% include 'tailwind/layout/help_text_and_errors.html' %}

    </{% if tag %}{{ tag }}{% else %}div{% endif %}>


{% endif %}

templates/others/tailwind/inputs.html
{% if inputs %}
    <div class="form-group{% if 'form-horizontal' in form_class %} row{% endif %}">
        {% if label_class %}
            <div class="aab {{ label_class }}"></div>
        {% endif %}

        <div class="{{ field_class }}">
            {% for input in inputs %}
                {% include "tailwind/layout/baseinput.html" %}
            {% endfor %}
        </div>
    </div>
{% endif %}

templates/others/tailwind/layout/baseinput.html
<input type="{{ input.input_type }}"
    name="{% if input.name|wordcount > 1 %}{{ input.name|slugify }}{% else %}{{ input.name }}{% endif %}"
    value="{{ input.value }}"
    {% if input.input_type != "hidden" %}
        class="{{ input.field_classes }}"
        id="{% if input.id %}{{ input.id }}{% else %}{{ input.input_type }}-id-{{ input.name|slugify }}{% endif %}"
    {% endif %}
    {{ input.flat_attrs|safe }}
    />

templates/others/tailwind/layout/button.html
<button {{ button.flat_attrs|safe }}>{{ button.content|safe }}</button>

templates/others/tailwind/layout/checkboxselectmultiple.html
{% load crispy_forms_filters %}
{% load l10n %}


{% for choice in field.field.choices %}
    <div class="mr-3">
        <label class="{% if css_container.option_label %}{{ css_container.option_label }}{% else %}block text-gray-700{% endif %}" for="id_{{ field.html_name }}_{{ forloop.counter }}">
            <input type="checkbox" class="{{ css_container.checkboxselectmultiple }}"{% if choice.0 in field.value or choice.0|stringformat:"s" in field.value or choice.0|stringformat:"s" == field.value|default_if_none:""|stringformat:"s" %} checked="checked"{% endif %} name="{{ field.html_name }}" id="id_{{ field.html_name }}_{{ forloop.counter }}" value="{{ choice.0|unlocalize }}" {{ field.field.widget.attrs|flatatt }}>
            {{ choice.1|unlocalize }}
        </label>
        {% if field.errors and forloop.last and not inline_class %}
            {# include 'tailwind/layout/field_errors_block.html' <-- bs4 template adds this here. Currently this pack adds it in field.html #}
        {% endif %}
    </div>
{% endfor %}
</div>

templates/others/tailwind/layout/column.html
<div {% if div.css_id %}id="{{ div.css_id }}"{% endif %}
     class="{{ div.css_class|default:'' }}" {{ div.flat_attrs|safe }}>
        {{ fields|safe }}
</div>

templates/others/tailwind/layout/field_errors.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-red-500 text-xs italic"><strong>{{ error }}</strong></p>
    {% endfor %}
{% endif %}

templates/others/tailwind/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-red-500 text-xs italic"><strong>{{ error }}</strong></p>
    {% endfor %}
{% endif %}

templates/others/tailwind/layout/field_with_buttons.html
{% load tailwind_field %}

<div{% if div.css_id %} id="{{ div.css_id }}"{% endif %} class="form-group{% if 'form-horizontal' in form_class %} row{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors and field.errors %} has-danger{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}{% if div.css_class %} {{ div.css_class }}{% endif %}" {{ div.flat_attrs|safe }}>
    {% if field.label and form_show_labels %}
        <label for="{{ field.id_for_label }}" class="{% if 'form-horizontal' in form_class %}col-form-label {% endif %}{{ label_class }}{% if field.field.required %} requiredField{% endif %}">
            {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
        </label>
    {% endif %}

    <div class="{{ field_class }}">
        <div class="input-group">
            {% crispy_field field %}
            <span class="input-group-append{% if active %} active{% endif %}{% if input_size %} {{ input_size }}{% endif %}">{{ buttons|safe }}</span>
        </div>
        {% include 'tailwind/layout/help_text_and_errors.html' %}
    </div>
</div>

templates/others/tailwind/layout/formactions.html
<div{% if formactions.attrs %} {{ formactions.flat_attrs|safe }}{% endif %} class="form-group{% if 'form-horizontal' in form_class %} row{% endif %}">
    {% if label_class %}
        <div class="aab {{ label_class }}"></div>
    {% endif %}

    <div class="{{ field_class }}">
        {{ fields_output|safe }}
    </div>
</div>

templates/others/tailwind/layout/help_text_and_errors.html
{% if help_text_inline and not error_text_inline %}
    {% include 'tailwind/layout/help_text.html' %}
{% endif %}

{% if error_text_inline %}
    {% include 'tailwind/layout/field_errors.html' %}
{% else %}
    {% include 'tailwind/layout/field_errors_block.html' %}
{% endif %}

{% if not help_text_inline %}
    {% include 'tailwind/layout/help_text.html' %}
{% endif %}

templates/others/tailwind/layout/inline_field.html
{% load tailwind_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div id="div_{{ field.auto_id }}" class="form-check form-check-inline{% if wrapper_class %} {{ wrapper_class }}{% endif %}">
            <label for="{{ field.id_for_label }}" class="form-check-label{% if field.field.required %} requiredField{% endif %}">
                {% crispy_field field 'class' 'form-check-input' %}
                {{ field.label|safe }}
            </label>
        </div>
    {% else %}
        <div id="div_{{ field.auto_id }}" class="input-group{% if wrapper_class %} {{ wrapper_class }}{% endif %}">
            <label for="{{ field.id_for_label }}" class="sr-only{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}
            </label>
            {% crispy_field field 'placeholder' field.label %}
        </div>
    {% endif %}
{% endif %}

templates/others/tailwind/layout/radioselect_inline.html
{% if field.is_hidden %}
    {{ field }}
{% else %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" class="{% if wrapper_class %}{{ wrapper_class }} {% endif %}{% if field_class %}{{ field_class }}{% else %}mb-3{% endif %}">

    {% if field.label %}
        <label for="{{ field.id_for_label }}"  class="{% if label_class %}{{ label_class }}{% else %}block text-gray-700 text-sm font-bold mb-2 {% endif %}{% if not inline_class %} col-form-label{% endif %}{% if field.field.required %} requiredField{% endif %}">
            {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
        </label>
    {% endif %}

    <div id="div_{{ field.auto_id }}" class="flex flex-row{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% include 'tailwind/layout/radioselect.html' %}
    </div>
{% endif %}

templates/others/tailwind/layout/row.html
<div {% if div.css_id %}id="{{ div.css_id }}"{% endif %} class="{{ div.css_class|default:'flex flex-row' }}" {{ div.flat_attrs|safe }}>
        {{ fields|safe }}
</div>

templates/others/tailwind/layout/select.html
{% load crispy_forms_filters %}
{% load l10n %}

<div class="relative">
<select class="{% if field.errors %}border border-red-500 {% endif %}bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700" name="{{ field.html_name }}" {{ field.field.widget.attrs|flatatt }}>
    {% for value, label in field.field.choices %}
        {% include "tailwind/layout/select_option.html" with value=value label=label %}
    {% endfor %}
</select>
<div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
  </div>
</div>
</div>

templates/others/tailwind/layout/select_option.html
{% load crispy_forms_filters %}
{% load l10n %}

<option value="{{ value|stringformat:'s' }}" {{ field.field.widget.attrs|flatatt }}{% if field.value == value %} selected{% endif %}>{{ label }}</option>

templates/others/tailwind/table_inline_formset.html
{% load crispy_forms_tags %}
{% load crispy_forms_utils %}
{% load tailwind_field %}

{% specialspaceless %}
{% if formset_tag %}
<form {{ flat_attrs|safe }} method="{{ form_method }}" {% if formset.is_multipart %} enctype="multipart/form-data"{% endif %}>
{% endif %}
    {% if formset_method|lower == 'post' and not disable_csrf %}
        {% csrf_token %}
    {% endif %}

    <div>
        {{ formset.management_form|crispy }}
    </div>

  {% include "tailwind/errors_formset.html" %}

    <table{% if form_id %} id="{{ form_id }}_table"{% endif%} class="table-auto">
        <thead>
            {% if formset.readonly and not formset.queryset.exists %}
            {% else %}
                <tr>
                    {% for field in formset.forms.0 %}
                        {% if field.label and not field.is_hidden %}
                            <th for="{{ field.auto_id }}" class="px-4 py-2">
                                {{ field.label|safe }}{% if field.field.required and not field|is_checkbox %}<span class="asteriskField">*</span>{% endif %}
                            </th>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endif %}
        </thead>

        <tbody>

            {% for form in formset %}
                {% if form_show_errors and not form.is_extra %}
                    {% include "tailwind/errors.html" %}
                {% endif %}

                <tr>
                    {% for field in form %}
                        {% include 'tailwind/field.html' with tag="td" form_show_labels=False field_class="border px-4 py-2" %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="mt-3">
    {% include "tailwind/inputs.html" %}
    </div>
{% if formset_tag %}</form>{% endif %}
{% endspecialspaceless %}

templates/shared/sidebar.html
<div x-show="sidebarOpen" class="bg-white h-screen w-72 overflow-y-scroll fixed z-50" @click.away="sidebarOpen = false">

    {# Main Sidebar Section #}
    <div class="mb-12 px-2">

        {# Home Link #}
        <a href="{% url 'core:index' %}"
           class="sidebar-links block">Home</a>

        {# Seperator #}
        <hr class="border-gray-300">

        {# Accounts Section #}
        <div x-data="{open: false}">
            {# Dropdown Section #}
            <div class="flex items-center sidebar-links" :class="{'bg-slate-100': open}" @click="open=!open">
                <span class="">
                    Accounts
                </span>
                <span class="grow"></span>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-caret-down block" viewBox="0 0 16 16" x-show="!open">
                    <path d="M3.204 5.296a.75.75 0 0 1 1.06 0L8 9.94l3.736-4.645a.75.75 0 1 1 1.12.98l-4.5 5.6a.75.75 0 0 1-1.12 0l-4.5-5.6a.75.75 0 0 1 0-.98z">
                    </path>
                </svg>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-caret-up block" viewBox="0 0 16 16" x-show="open">
                    <path d="M12.736 10.645a.75.75 0 0 1-1.06 0L8 6.06 4.324 10.645a.75.75 0 1 1-1.12-.98l4.5-5.6a.75.75 0 0 1 1.12 0l4.5 5.6a.75.75 0 0 1 0 .98z">
                    </path>
                </svg>

            </div>
            {# Menu Section #}
            <div x-show="open" class="pl-3">
                <a href="{% url 'accounts:change-password' %}" class="sidebar-sublinks block">Change Password</a>
                <a href="{% url 'accounts:logout' %}" class="sidebar-sublinks block">Logout</a>
            </div>
        </div>

    </div>

    {# Email #}
    <dib class="fixed bottom-0 left-0 bg-slate-50 border-t border-slate-300 py-2 w-72 px-5">
        {{ request.user.email }}
    </dib>
</div>
<div class="w-screen h-screen z-40 fixed bg-gray-800 opacity-25" x-show="sidebarOpen">
</div>